#ifndef ERRORS_H
#define ERRORS_H

enum error_e {
  ERR_SUCCESS,
  ERR_MALLOC,
  ERR_PTRACE_SETOPTIONS,
  ERR_PTRACE_ATTACH,
  ERR_PTRACE_SYSCALL,
  ERR_PTRACE_GETREGS,
  ERR_PTRACE_PEEKTEXT,
  ERR_PTRACE_POKETEXT,
  ERR_PTRACE_SETREGS,
  ERR_PTRACE_TRACEME,
  ERR_PTRACE_GETEVENTMSG,
  ERR_TERMINATED,
  ERR_KILLED,
  ERR_EXECVP,
  ERR_FORK,
  ERR_WAITPID,
  ERR_TOOFEWARGS,
  ERR_FILLED_DESCS,
  ERR_OPENSTDIN,
  ERR_OPENSTDOUT,
  ERR_OPENSTDERR,
  ERR_EFORK,
  ERR_EVFORK,
  ERR_ECLONE
};

#endif
